### ISSUE TITLE
Support for v2 Quasar (Vue 3)

### ISSUE THREAD

**Issue by Karnith** [quasarframework/quasar-ui-qactivity#27]
Hi, I currently get an error compiling my project. The error states that qactivity doesn't support v2 of quasar. When will it be supported?

**Comment by hawkeye64** [comment]
It'll be supported once Quasar v2 is out of beta.

**Comment by har1s1m** [comment]
also, received an error after upgrade to v3.  @hawkeye64 will it be supported?

**Comment by hawkeye64** [comment]
@har1s1m Yes, it's on the (long!) list. But, I am on vacation this week with little to no mobile signal.

**Comment by hawkeye64** [comment]
It's being worked on right now.

**Comment by hawkeye64** [comment]
This is resolved with v2.0.0-alpha.1
Install with:

```js
quasar ext add @quasar/qactivity@next
```
